name: funday_media
description: "Travel Audio App."

version: 1.0.0+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0-dev.17

  dio: ^5.9.0
  retrofit: ^4.2.0
  logger: any  #for logging purpose
  json_annotation: ^4.9.0
  http_parser: any
  path_provider: ^2.1.5
  flutter_easyloading: ^3.0.5
  go_router: ^16.2.0

  drift: ^2.16.0
  drift_flutter: ^0.2.0
  path: ^1.9.1

  intl: ^0.20.2
  audioplayers: ^6.5.0
  synchronized: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^10.0.0
  # JSON BUILDER
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  test: ^1.25.2

  # DB
  drift_dev: ^2.16.0

  flutter_lints: ^6.0.0
  riverpod_lint: ^3.0.0-dev.17
  custom_lint: ^0.8.0

analyzer:
  plugins:
    - custom_lint

flutter:
  uses-material-design: true
